name: $(date:yyyyMMdd)$(rev:.rr)

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - client

pool: "devops-agent"

resources:
  repositories:
    - repository: templates
      type: git
      name: PRODUCT_DEVELOPMENT/PRODUCT_DEVELOPMENT

variables:
  - group: Deploy

stages:
  - stage: Build
    jobs:
      - template: azure-pipelines/build-docker-many.yml@templates
        parameters:
          App: seefit
          ServiceList:
            - "client/web"

  - stage: Deploy_tst
    displayName: "Deploy: Testing"
    dependsOn: Build
    condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest'))
    jobs:
      - template: azure-pipelines-v2/deploy-tst.yml@templates
        parameters:
          Dir: "client"
          Namespace: "seefit"
          InstallList:
            - "client"
          EnsureDeployments:
            - "web"

  - stage: Native
    displayName: "Cordova"
    dependsOn: Build
    jobs:
      - job: Prepare
        steps:
          - task: Docker@2
            displayName: Login
            inputs:
              command: login
              containerRegistry: azurecr

          - bash: |
              CONTAINER=$(docker run -d --rm inovretail.azurecr.io/seefit/client/web:${BUILD_BUILDNUMBER})
              docker cp ${CONTAINER}:/usr/share/nginx/html www
              tar -czf www.tar.gz www
            workingDirectory: "$(Build.ArtifactStagingDirectory)"
            displayName: "Web package"

          - publish: $(Build.ArtifactStagingDirectory)/www.tar.gz
            artifact: web

          - bash: |
              if [ $BUILD_REASON -eq 'PullRequest' ];
              then
                echo "##vso[task.setvariable variable=env;isreadonly=true;isoutput=true]tst"
                exit 0
              fi

              if [ $BUILD_REASON -eq 'IndividualCI' ];
              then
                echo "##vso[task.setvariable variable=env;isreadonly=true;isoutput=true]prd"
              fi

              exit 1
            displayName: "Set $ENV"
            name: setenv

      - job: Android
        dependsOn: Prepare
        variables:
          env: $[ dependencies.Prepare.outputs['setenv.env'] ]
        steps:
          - checkout: self

          - download: current
            artifact: web

          - task: Docker@2
            displayName: Login
            inputs:
              command: login
              containerRegistry: azurecr

          - bash: |
              rm -rf dist
              rm -rf www
              tar -xzf ${PIPELINE_WORKSPACE}/web/www.tar.gz

              echo "ENV=$ENV"

              docker build \
                --build-arg DEVOPS_FEED_READ_TOKEN=ZzdnemoybXlkb2Vnc2pjZmx2bW8zdjZkYmo3bWN0NnZ6NTZsam1pbmRtcmg0aHN6eW9tcQ== \
                --build-arg BUILD_BUILDID=${BUILD_BUILDID} \
                --build-arg BUILD_BUILDNUMBER=${BUILD_BUILDNUMBER} \
                --build-arg ENV=${ENV} \
                -t seefit . || exit 1
              CONTAINER=$(docker run -d seefit)

              echo "Get build artifacts"
              docker cp $CONTAINER:/dist .

              ls -l
              echo "-- dist --"
              ls -l dist
              
            workingDirectory: $(Build.SourcesDirectory)/client/native
            displayName: "Create Package"

          - publish: $(Build.SourcesDirectory)/client/native/dist
            artifact: native-android

  - stage: Deploy_prd
    displayName: "Deploy: Production"
    dependsOn: Build
    condition: and(succeeded(), eq(variables['Build.Reason'], 'IndividualCI'))
    jobs:
      - template: azure-pipelines-v2/deploy-prd.yml@templates
        parameters:
          Dir: "client"
          Namespace: "seefit"
          InstallList:
            - "client"
          EnsureDeployments:
            - "web"
