apiVersion: v1
kind: Service
metadata:
  name: client
  labels:
    app: client
spec:
  ports:
    - name: http
      port: 80
  selector:
    app: client

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  labels:
    app: client
spec:
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      imagePullSecrets:
        - name: azurecr
      restartPolicy: Always
      containers:
        - name: client
          image: inovretail.azurecr.io/seefit/client:${TAG}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: 64Mi
              cpu: "0.05"
            limits:
              memory: 128Mi
              cpu: "0.1"
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: client
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: client
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
