apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app : client  
    spec:
      containers:
        - name: client
          image: inovretail.azurecr.io/seefit/client:${TAG}
          imagePullPolicy: Always
          ports:
          - containerPort: 80