apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app : web  
    spec:
      containers:
        - name: web
          image: inovretail.azurecr.io/seefit/web:${TAG}
          imagePullPolicy: Always
          ports:
          - containerPort: 80