name: $(date:yyyyMMdd)$(rev:.rr)

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - middleware

pool: "cicd-agent"

resources:
  repositories:
    - repository: templates
      type: git
      name: PRODUCT_DEVELOPMENT/PRODUCT_DEVELOPMENT

variables:
  - group: Deploy

stages:
  - stage: Build
    jobs:
      - template: azure-pipelines/build-docker-many.yml@templates
        parameters:
          App: seefit
          ServiceList:
            - "middleware"

  - stage: Deploy_tst
    displayName: "Deploy: Testing"
    dependsOn: Build
    condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest'))
    jobs:
      - template: azure-pipelines-v2/deploy-tst.yml@templates
        parameters:
          Dir: "middleware"
          Namespace: "seefit"
          InstallList:
            - "middleware"
          EnsureDeployments:
            - "middleware"

  - stage: Deploy_prd
    displayName: "Deploy: Production"
    dependsOn: Build
    condition: and(succeeded(), eq(variables['Build.Reason'], 'IndividualCI'))
    jobs:
      - template: azure-pipelines-v2/deploy-prd.yml@templates
        parameters:
          Dir: "middleware"
          Namespace: "seefit"
          InstallList:
            - "middleware"
          EnsureDeployments:
            - "middleware"
