apiVersion: v1
kind: Service
metadata:
  name: middleware
  labels:
    app: middleware
spec:
  ports:
    - name: http
      port: 80
  selector:
    app: middleware

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: middleware
  labels:
    app: middleware
spec:
  selector:
    matchLabels:
      app: middleware
  template:
    metadata:
      labels:
        app: middleware
    spec:
      imagePullSecrets:
        - name: azurecr
      restartPolicy: Always
      containers:
        - name: middleware
          image: inovretail.azurecr.io/seefit/middleware:${TAG}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: API_GATEWAY
              value: http://gateway.${NS_PREFIX}api
          resources:
            requests:
              memory: 64Mi
              cpu: "0.05"
            limits:
              memory: 128Mi
              cpu: "0.1"
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: middleware
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: middleware
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
