name: $(date:yyyyMMdd)$(rev:.rr)
trigger:
  branches:
    include:
      - main
  paths:
    include:
      - __kube

pool: "devops-agent"

resources:
  repositories:
    - repository: templates
      type: git
      name: PRODUCT_DEVELOPMENT/PRODUCT_DEVELOPMENT

variables:
  - group: Deploy

stages:
  - stage: Deploy_tst
    displayName: "Deploy: Testing"
    condition: eq(variables['Build.Reason'], 'PullRequest')
    jobs:
      - template: azure-pipelines-v2/deploy-tst.yml@templates
        parameters:
          Namespace: "seefit"
          InstallNamespace: true
          InstallSecret: false
          InstallList:
            - "ingress"
            - "gateway"
          EnsureDeployments:
            - "gateway"

  - stage: Deploy_prd
    displayName: "Deploy: Production"
    condition: eq(variables['Build.Reason'], 'IndividualCI')
    jobs:
      - template: azure-pipelines-v2/deploy-prd.yml@templates
        parameters:
          Namespace: "seefit"
          InstallNamespace: true
          InstallSecret: false
          InstallList:
            - "ingress"
            - "gateway"
          EnsureDeployments:
            - "gateway"
