apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-kong-env
data:
  KONG_ADMIN_LISTEN: "0.0.0.0:8001"
  KONG_PROXY_LISTEN: "0.0.0.0:8000"
  KONG_SSL: "off"
  KONG_ADMIN_SSL: "off"
  KONG_DATABASE: "off"
  KONG_DECLARATIVE_CONFIG: /kong-config/kong.yaml
  KONG_LOG_LEVEL: "info"
  KONG_PROXY_ACCESS_LOG: "/proc/1/fd/1"
  KONG_PROXY_ERROR_LOG: "/proc/1/fd/2"
  KONG_ADMIN_ACCESS_LOG: "/proc/1/fd/1"
  KONG_ADMIN_ERROR_LOG: "/proc/1/fd/2"
  KONG_ANONYMOUS_REPORTS: "off"
  KONG_NGINX_WORKER_PROCESSES: "1"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-kong-config
data:
  kong.yaml: |
    _format_version: "1.1"
    services:
      - name: middleware
        url: http://middleware:80/
        routes:
          - name: middleware_base
            paths:
              - /middleware
      - name: client-web
        url: http://client-web:80/
        routes:
          - name: client-web
            paths:
              - /
    plugins:
      - name: request-size-limiting
        config:
          allowed_payload_size: 10
          size_unit: megabytes
      - name: bot-detection
      - name: correlation-id
        config:
          header_name: x-log-id
          generator: uuid
          echo_downstream: false
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8000
    - name: admin
      port: 8001
      targetPort: 8001
  selector:
    app: gateway

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  selector:
    matchLabels:
      app: gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway
    spec:
      imagePullSecrets:
        - name: azurecr
      containers:
        - name: gateway
          image: inovretail.azurecr.io/ext/kong:2.8.1-alpine
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "250m"
              memory: 512Mi
            limits:
              cpu: "500m"
              memory: 1024Mi
          ports:
            - containerPort: 8000
            - containerPort: 8001
          envFrom:
            - configMapRef:
                name: gateway-kong-env
          volumeMounts:
            - name: kong-config
              mountPath: /kong-config

      volumes:
        - name: kong-config
          configMap:
            name: gateway-kong-config
