apiVersion: v1
kind: Pod
metadata:
  name: gateway-config
  labels:
    app: gateway-config
spec:
  imagePullSecrets:
  - name: azurecr
  restartPolicy: OnFailure
  containers:
  - name: gateway-config
    image: inovretail.azurecr.io/seefit/gateway-config:${TAG}
    imagePullPolicy: Always
    env:
    - name: ENV
      value: DEV

    - name: KONG_URI
      value: gateway.${NS_PREFIX}api:8001

    - name: NS_PREFIX
      value: ${NS_PREFIX}

